# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - '*'
    exclude:
    - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: jasonbbbbbb 
  imageName: 'nodejs.org:$(build.sourceBranchName)'

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)